### ISSUE TITLE
Error if "repos" list is present but empty

### ISSUE THREAD

**Issue by cillian64** [HarkonenBade/github-backup#11]
```
 dwt27@moorhen.dwt27.co.uk  ~/g/github-backup  ./github-backup.py      master  15:24:33
Traceback (most recent call last):
  File "./github-backup.py", line 208, in <module>
    main()
  File "./github-backup.py", line 186, in main
    for name, repo in ghub_repos.items()
  File "./github-backup.py", line 187, in <listcomp>
    if name not in conf_repos]
TypeError: argument of type 'NoneType' is not iterable
```

This occurs if github-backup.yml contains an empty "repos" list.  The script works correctly if the repos list is absent, but not if it exists but is empty.

**Comment by HarkonenBade** [comment]
What do you mean by 'empty'? Can you show a redacted copy of the conf file?

**Comment by cillian64** [comment]
File contents:
```
exclude: [agg-kicad, weather-plots, cvxpy, cvxopt, rsmpi, Mk2-Firmware, fidget, dtg-weather-2,
  libopencm3]
general: {only_personal: true, repopath: /home/dwt27/github-backup, token: XXXXX,
  unknown_repo_warning: 1}
repos:
```

This may be a silly state for things to be in, but it seemed like a sensible way for me to reset the repos without wiping my auth key.

**Comment by HarkonenBade** [comment]
Ah, ok. Slightly surprised that that is valid YAML but sure. I'll add a check in the conf reader for None type returns as there shouldn't be any in practice.
