### ISSUE TITLE
Output formatting things

### ISSUE THREAD

**Issue by cillian64** [HarkonenBade/github-backup#5]
- [ ] Cloning says HTTPS even when it's cloning over SSH??
 - [x] Include repo description and URL in interactive mode
 - [x] Put some newlines between things for each repo so I don't get a wall of text
 - [x] Yes/No/Skip or Yes/No/Exclude?
 - [x] Maybe do all the interactive stuff first and then clone everything at the end, so I don't have to wait for cloning while configuring. Maybe even clone in parallel!!

**Comment by HarkonenBade** [comment]
Clone url reporting was due to a fail at live editing
